apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: org1
  name: nfs-bc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.99.1
    path: "/export/data/"